name: 'nikkiso_analytics'
version: '1.0.0'
config-version: 2

profile: 'nikkiso_snowflake'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nikkiso_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  nikkiso_analytics:
    +schema: staging
    +quote_columns: false
